kd_approach: KD
alpha: 1
beta: 1

#  optimization
weight_decay: 0.0005 #error with 5e-4
momentum: 0.9
lr: 0.05
lr_decay_rate: 0.1
lr_decay_epochs: 
  - 60
  - 80
  #- 100

# freq_config: 
print_freq: 100 
save_freq: 50

epochs: 100
max_step: 3
step_patience: 1

save_folder: ./data/