#  optimization
weight_decay: 0.0005 #error with 5e-4
momentum: 0.9
lr: 0.05
lr_decay_rate: 0.1
lr_decay_epochs: 
  - 60
  - 80

# freq_config: 
print_freq: 50 
save_freq: 50

epochs: 2

save_folder: ./data/